apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-dev
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: cithit/roseaw:latest  # Jenkins will replace this tag dynamically
        ports:
        - containerPort: 5000
